name: Fetch Repository Stats
concurrency: fetch-repository-stats

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  run-ghrs-with-matrix:
    name: repostats-for-nice-projects
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # The repositories to generate reports for.
        statsRepo: [
          'rgglez/git-scripts',
          'rgglez/python-gpt-po',
          'rgglez/ansible-scripts',
          'rgglez/gofiber-recaptcha3-middleware',
          'rgglez/fc-gomail',
          'rgglez/yii-svelte-simpleautocomplete',
          'rgglez/smelte',
          'rgglez/cloudflare-scripts',
          'rgglez/gettext-spellchecker',
          'rgglez/yii-emailsintaxvalidator',
          'rgglez/rgglez-cs-thesis-scip',
          'rgglez/gofiber-zitadel-middleware',
          'rgglez/yii-ftpassetmanager',
          'rgglez/gettext-translator',
          'rgglez/yii-emailsmtpvalidator',
          'rgglez/yama',
          'rgglez/ssl-validator',
          'rgglez/go-playground-recaptcha3-validator',
          'rgglez/intldate',
          'rgglez/nagios-check-ssl-expiration',
          'rgglez/yii-htmlpurifier',
          'rgglez/3ds-varitech',
          'rgglez/lambda-html-tidy',
          'rgglez/fc-webpage-screenshot',
          'rgglez/fc-exchange-rate-update',
          'rgglez/go-config',
          'rgglez/svelte-frappe-charts',
          'rgglez/storage',
          'rgglez/webkit2png-daemon',
          'rgglez/mysql-encrypted-backup',
          'rgglez/ndjbdns-scripts',
          'rgglez/yii-jui',
          'rgglez/jabberd2-auth-linux.patch',
          'rgglez/nagios-check-domain-ai',
          'rgglez/nagios-check-ping-go',
          'rgglez/gofiber-roles-middleware',
          'rgglez/yii-webfeed',
          'rgglez/gofiber-validator-middleware',
          'rgglez/gettext-po2json',
          'rgglez/whois-parser-ai',
          'rgglez/svelte-i18n',
          'rgglez/fc-certbot',
          'rgglez/rgglez-website',
          'rgglez/gettext-extractor',
          'rgglez/svelte-i18n-gettext',
          'rgglez/svelte-mediaquery',
          'rgglez/gofiber-recovery-middleware',
          'rgglez/ai-whois-parser',
          'rgglez/Spreadsheet_Excel_Writer',
          'rgglez/php5-ext-crack2',
          'rgglez/cs-prenex',
          'rgglez/letsencrypt-scripts',
          'rgglez/go-database',
          'rgglez/gofiber-ip-middleware',
          'rgglez/svelte-seo',
          'rgglez/asm-editor',
          'rgglez/music-keyboard',
          'rgglez/go-storage',
          'rgglez/cs-automata-theory',
          'rgglez/nagios-check-domain',
          'rgglez/yii-emailvalidator',
          'rgglez/aliyun-scripts',
          'rgglez/asm-8085',
          'rgglez/gormcache',
          'rgglez/games-syg',
          'rgglez/svelte-alerts',
          'rgglez/eBBS']
      # Do not cancel&fail all remaining jobs upon first job failure.
      fail-fast: false
      # Help avoid commit conflicts. Note(JP): this should not be
      # necessary anymore, feedback appreciated
      max-parallel: 1
    steps:
      - name: run-ghrs
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: ${{ matrix.statsRepo }}
          ghtoken: ${{ secrets.ghrs_github_api_token }}
