name: fetch-repository-stats
concurrency: fetch-repository-stats

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  run-ghrs-with-matrix:
    name: repostats-for-nice-projects
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # The repositories to generate reports for.
        statsRepo: [
          'rgglez/3ds-varitech/',
          'rgglez/ai-whois-parser/',
          'rgglez/aliyun-scripts/',
          'rgglez/ansible-scripts/',
          'rgglez/asm-8085/',
          'rgglez/asm-editor/',
          'rgglez/cloudflare-scripts/',
          'rgglez/cs-automata-theory/',
          'rgglez/cs-prenex/',
          'rgglez/fc-certbot/',
          'rgglez/fc-exchange-rate-update/',
          'rgglez/fc-gomail/',
          'rgglez/fc-webpage-screenshot/',
          'rgglez/gettext-extractor/',
          'rgglez/gettext-po2json/',
          'rgglez/gettext-spellchecker/',
          'rgglez/gettext-translator/',
          'rgglez/git-scripts/',
          'rgglez/go-config/',
          'rgglez/go-database/',
          'rgglez/gofiber-ip-middleware/',
          'rgglez/gofiber-recaptcha3-middleware/',
          'rgglez/gofiber-recovery-middleware/',
          'rgglez/gofiber-roles-middleware/',
          'rgglez/gofiber-validator-middleware/',
          'rgglez/gofiber-zitadel-middleware/',
          'rgglez/go-playground-recaptcha3-validator/',
          'rgglez/gormcache/',
          'rgglez/go-storage/',
          'rgglez/intldate/',
          'rgglez/jabberd2-auth-linux.patch/',
          'rgglez/lambda-html-tidy/',
          'rgglez/letsencrypt-scripts/',
          'rgglez/music-keyboard/',
          'rgglez/mysql-encrypted-backup/',
          'rgglez/nagios-check-domain/',
          'rgglez/nagios-check-domain-ai/',
          'rgglez/nagios-check-ping-go/',
          'rgglez/nagios-check-ssl-expiration/',
          'rgglez/ndjbdns-scripts/',
          'rgglez/php5-ext-crack2/',
          'rgglez/python-gpt-po/',
          'rgglez/rgglez-cs-thesis-scip/',
          'rgglez/rgglez-website/',
          'rgglez/Spreadsheet_Excel_Writer/',
          'rgglez/storage/',
          'rgglez/svelte-alerts/',
          'rgglez/svelte-frappe-charts/',
          'rgglez/svelte-i18n/',
          'rgglez/svelte-i18n-gettext/',
          'rgglez/svelte-mediaquery/',
          'rgglez/svelte-seo/',
          'rgglez/webkit2png-daemon/',
          'rgglez/whois-parser-ai/',
          'rgglez/yii-emailsintaxvalidator/',
          'rgglez/yii-emailsmtpvalidator/',
          'rgglez/yii-emailvalidator/',
          'rgglez/yii-ftpassetmanager/',
          'rgglez/yii-htmlpurifier/',
          'rgglez/yii-jui/',
          'rgglez/yii-svelte-simpleautocomplete/',
          'rgglez/yii-webfeed/']
      # Do not cancel&fail all remaining jobs upon first job failure.
      fail-fast: false
      # Help avoid commit conflicts. Note(JP): this should not be
      # necessary anymore, feedback appreciated
      max-parallel: 1
    steps:
      - name: run-ghrs
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: ${{ matrix.statsRepo }}
          ghtoken: ${{ secrets.ghrs_github_api_token }}
