name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&bg_color=00000000
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=8&bg_color=00000000
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate gettext-translator pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: bg_color=00000000&description_lines_count=2&username=${{ github.repository_owner }}&repo=gettext-translator
          path: profile/pin-gettext-translator-github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate svelte-i18n-gettext pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: bg_color=00000000&description_lines_count=2&username=${{ github.repository_owner }}&repo=svelte-i18n-gettext
          path: profile/pin-svelte-i18n-gettext-github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate geonames-loader pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: bg_color=00000000&description_lines_count=2&username=${{ github.repository_owner }}&repo=geonames-loader
          path: profile/pin-geonames-loader-github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate gettext-spellchecker pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: bg_color=00000000&description_lines_count=2&username=${{ github.repository_owner }}&repo=gettext-spellchecker
          path: profile/pin-gettext-spellchecker-github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate gormcache pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: bg_color=00000000&description_lines_count=2&username=${{ github.repository_owner }}&repo=gormcache
          path: profile/pin-gormcache-github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate yii-webfeed pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: bg_color=00000000&description_lines_count=2&username=${{ github.repository_owner }}&repo=yii-webfeed
          path: profile/pin-yii-webfeed-github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate go-storage pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: bg_color=00000000&description_lines_count=2&username=${{ github.repository_owner }}&repo=go-storage
          path: profile/pin-go-storage-github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate whois-parser-ai pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: bg_color=00000000&description_lines_count=2&username=${{ github.repository_owner }}&repo=whois-parser-ai
          path: profile/pin-whois-parser-ai-github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate gormcache pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: bg_color=00000000&description_lines_count=2&username=${{ github.repository_owner }}&repo=whois-parser-ai
          path: profile/pin-whois-parser-ai-github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate nagios-check-ssl-expiration pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: bg_color=00000000&description_lines_count=2&username=${{ github.repository_owner }}&repo=nagios-check-ssl-expiration
          path: profile/pin-nagios-check-ssl-expiration-github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate nagios-check-domain pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: bg_color=00000000&description_lines_count=2&username=${{ github.repository_owner }}&repo=nagios-check-domain
          path: profile/pin-nagios-check-domain-github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate gofiber-recovery-middleware pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: bg_color=00000000&description_lines_count=2&username=${{ github.repository_owner }}&repo=gofiber-recovery-middleware
          path: profile/pin-gofiber-recovery-middleware-github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate gofiber-recaptcha3-middleware pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: bg_color=00000000&description_lines_count=2&username=${{ github.repository_owner }}&repo=gofiber-recaptcha3-middleware
          path: profile/pin-gofiber-recaptcha3-middleware-github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push